---
title: "Liela"
author: "liela"
date: "3/1/2021"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(tidyverse)
library(dplyr)
library(zoo)
library(gridExtra)
library(scales)
library(lubridate)
library(ggplot2)
library(plm)
# set up
covid <- read_csv("https://covid19.who.int/WHO-COVID-19-global-data.csv")
covid[which(covid$Country == "The United Kingdom"), "Country"] = "UK"
quarantine <- read_csv("stay_at_home_requirements.csv") %>% select(-X1, -country_code)
quarantine[which(quarantine$Entity == "United Kingdom"), "Entity"] = "UK"
# minor adjusting
quarantine <- quarantine  %>% 
  pivot_longer(
    cols = -country_name,
    names_to = "day",
    values_to = "flag"
  ) %>% mutate(flag=as.factor(flag), Date_reported=lubridate::dmy(day)) 
quarantine <- quarantine %>% select(-day)%>% rename(Country=country_name)
covid <- covid %>% select(-Country_code, -WHO_region)
data <- covid %>% inner_join(quarantine,by=c("Country", "Date_reported"))
# Target period of analysis: 2020-10-01 to 2020-11-30
# Target country: Germany, UK, France, Italy, Poland
covid_window <- data %>% dplyr::filter(Country %in% c("Germany", "UK", "France", "Italy", "Poland") &Date_reported>"2020-09-15" &Date_reported<"2020-12-07")

# virus incubation period d = 7
# I_(t-d-1) = y_(t-1) - y_(t-d-1), where y is cumulative cases
# delta_I_t = [y_t - y_(t-d)] - [y_(t-1)-y_(t-d-1)] = new_cases_t - new_cases_(t-d)
covid_model.d7 <- covid_window %>% 
  group_by(Country) %>% 
  mutate(New_infectious = New_cases - lag(New_cases,7),
         lag_infectious = Cumulative_cases - lag(Cumulative_cases,7))

# calculating 3, 5, 7-day moving average of new_infectious and cum_infectious
covid_model.d7 <- covid_model.d7 %>% 
  group_by(Country) %>% 
  mutate(New_infec_07ma = zoo:: rollmean(New_infectious,k=7,fill=NA),
         lag_infec_07ma = zoo:: rollmean(lag_infectious,k=7,fill=NA),
         New_infec_05ma = zoo:: rollmean(New_infectious,k=5,fill=NA),
         lag_infec_05ma = zoo:: rollmean(lag_infectious,k=5,fill=NA),
         New_infec_03ma = zoo:: rollmean(New_infectious,k=3,fill=NA),
         lag_infec_03ma = zoo:: rollmean(lag_infectious,k=3,fill=NA)) %>%
  dplyr::ungroup()

covid_model.d7 <- covid_model.d7 %>% 
  filter(covid_model.d7$Date_reported>"2020-09-30" & 
           covid_model.d7$Date_reported<"2020-12-01")
range(covid_model.d7$Date_reported) # 2020-10-01 to 2020-11-30

# Calculate response variable: delta_infectious
covid_model.d7 <- covid_model.d7 %>% 
  mutate(delta_infectious = 100*New_infectious/lag_infectious, 
         delta_infec_07ma = 100*New_infec_07ma/lag_infec_07ma, 
         delta_infec_05ma = 100*New_infec_05ma/lag_infec_05ma, 
         delta_infec_03ma = 100*New_infec_03ma/lag_infec_03ma)
```
```{r plot}
# plot of delta_infectious vs. date
plot(covid_model.d7$Date_reported,covid_model.d7$delta_infec_05ma, 
     type="p",cex=0.3,
     main = expression(paste("%", Delta, y[ct], " by Date")),
     xlab = "Date",
     ylab = expression(paste("%", Delta, y[ct])))

# Bar charts
ggplot(
  data = covid_model.d7,
  mapping = aes(
    x = Date_reported,
    y = New_cases,
    fill = flag
  )
) +
  geom_bar(
    stat = "identity"
  ) +
  labs(
    title = "COVID-19 daily cases and stay-at-home requirement in Oct-Nov 2020",
    x = "Date",
    y = "Country",
    fill = "Restriction"
  ) +
  facet_grid(
    rows = vars(Country),
    scales = "free"
  ) +
  theme(
    legend.position = "bottom"
  )
```
```{r plm}
library(plm)
plm_new_death <- plm(delta_infec_03ma~flag,data=covid_model.d7,index=c("Country", "Date_reported"),model="within")
########## model testing ########
# Display the fixed effects (constants for each country)
fixef(plm_new_death)
#  Testing for fixed effects, null: OLS better than fixed
ols <- lm(delta_infec_03ma~flag,data=covid_model.d7)
pFtest(plm_new_death, ols)                          # ------- fixed effect model better 
# Hausman test: fixed vs random model
random <- plm(delta_infec_03ma~flag,data=covid_model.d7,index=c("Country", "Date_reported"),model="random")
phtest(plm_new_death, random)                       # ------ choose random model 
# Testing for time-fixed effects
time <- plm(delta_infec_03ma~flag+Date_reported,data=covid_model.d7,index=c("Country", "Date_reported"),model="within")
pFtest(time,random)
plmtest(random, c("time"), type=("bp"))      # ----no need to use time-fixed effects
# compare
summary(plm_new_death)
summary(random)
# Inference for Estimated Coefficients
lmtest::coeftest(random)
lmtest::coefci(random)
```

```{r world_plot}
covid_model.d7 %>%
  group_by(Date_reported) %>%
  e_chart(Country, timeline = TRUE) %>%
  e_map(delta_infec_03ma) %>%
  e_visual_map(min= -20, max= 20,
               type = 'piecewise') %>%
  e_title("delta_infec_03ma", left = "center") %>%
  e_tooltip(
    trigger = "item",
    formatter = e_tooltip_choro_formatter())
```


